# Generated by Django 4.1.3 on 2022-11-28 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
