# Generated by Django 4.1.3 on 2022-12-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0002_flight_date_flight_passengers_option_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='airsite.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='airsite.seat'),
        ),
    ]
