# Generated by Django 4.1.3 on 2022-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0003_seat_flight_booked_seats_alter_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
    ]
