# Generated by Django 4.1.3 on 2022-12-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0004_seat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='airsite.option'),
        ),
    ]
