# Generated by Django 4.1.3 on 2022-12-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0005_alter_ticket_name_alter_ticket_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='airsite.seat'),
        ),
    ]
