# Generated by Django 4.1.3 on 2022-12-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0006_alter_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='option_2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket2', to='airsite.option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket1', to='airsite.option'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='airsite.seat', to_field='name'),
        ),
    ]
