# Generated by Django 4.1.3 on 2022-12-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0008_alter_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
