# Generated by Django 4.1.3 on 2022-12-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0011_alter_ticket_options_remove_ticket_is_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('ticket_gate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='airsite.gateregistration')),
            ],
        ),
    ]
