# Generated by Django 4.1.3 on 2022-12-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0013_remove_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
    ]
