# Generated by Django 4.1.3 on 2022-12-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0014_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket1', to='airsite.option'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket2', to='airsite.option'),
        ),
    ]
