# Generated by Django 4.1.3 on 2022-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsite', '0015_alter_ticket_option_alter_ticket_option_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
